language: cpp
compiler:
    - gcc
before_install:
    - sudo pip install cpp-coveralls
script:
    - make
    - ./test/HeapTest 10
    - ./test/HeapTest 100
    - ./test/HeapTest 1000
after_success:
    - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
